-Trying to run Browserstack inside Circle CI

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -652,22 +652,6 @@ jobs:
     steps:
         - run:
             <<: ./gradlew assembleDebug
-        - run:
-            name: App upload and Set app id in environment variable.
-            command: |
-              APP_UPLOAD_RESPONSE=$(curl -u "denilsonsilva1:nDYNkqHHwAnLVDACdzKq" -X POST https://api-cloud.browserstack.com/app-automate/upload -F "file=@app/build/outputs/apk/debug/app-debug.apk")
-              APP_ID=$(echo $APP_UPLOAD_RESPONSE | jq -r ".app_url")
-              if [ $APP_ID != null ]; then
-                echo "Apk uploaded to BrowserStack with app id : ",$APP_ID;
-                echo "export BROWSERSTACK_APP_ID=$APP_ID" >> $BASH_ENV;
-                source $BASH_ENV;
-                echo "Setting value of BROWSERSTACK_APP_ID in environment variables to  ",$APP_ID;
-              else
-                UPLOAD_ERROR_MESSAGE=$(echo $APP_UPLOAD_RESPONSE | jq -r ".error")
-                echo "App upload failed, reason : ",$UPLOAD_ERROR_MESSAGE
-                exit 1;
-              fi
-
       - run:
           <<: *run_log_mem_use
       - run:
@@ -680,6 +664,18 @@ jobs:
       - run:
           name: "Running self-test (Browserstack Test)"
           command: |
+            APP_UPLOAD_RESPONSE=$(curl -u "denilsonsilva1:nDYNkqHHwAnLVDACdzKq" -X POST https://api-cloud.browserstack.com/app-automate/upload -F "file=@app/build/outputs/apk/debug/app-debug.apk");
+            APP_ID=$(echo $APP_UPLOAD_RESPONSE | jq -r ".app_url");
+            if [ $APP_ID != null ]; then
+              echo "Apk uploaded to BrowserStack with app id : ",$APP_ID;
+              echo "export BROWSERSTACK_APP_ID=$APP_ID" >> $BASH_ENV;
+              source $BASH_ENV;
+              echo "Setting value of BROWSERSTACK_APP_ID in environment variables to  ",$APP_ID;
+            else
+              UPLOAD_ERROR_MESSAGE=$(echo $APP_UPLOAD_RESPONSE | jq -r ".error")
+              echo "App upload failed, reason : ",$UPLOAD_ERROR_MESSAGE
+              exit 1;
+            fi
             TEST_GROUP='css hot code push|custom minifier - devel vs prod|versioning hot code push|javascript hot code push|add packages client archs';
             echo $TEST_GROUP;
             eval $PRE_TEST_COMMANDS;
