Ensure launch-meteor temporary files always get cleaned up.

diff --git a/scripts/admin/launch-meteor b/scripts/admin/launch-meteor
--- a/scripts/admin/launch-meteor
+++ b/scripts/admin/launch-meteor
@@ -73,7 +73,23 @@ if [ ! -x "$METEOR_WAREHOUSE_DIR/meteor" ]; then
   TARBALL_URL="${TMP_ROOT_URL}/meteor-bootstrap-${PLATFORM}.tar.gz"
 
   INSTALL_TMPDIR="$(dirname "$METEOR_WAREHOUSE_DIR")/.meteor-install-tmp"
-  rm -rf "$INSTALL_TMPDIR"
+
+  # Generate the $TARBALL_FILE path based on $TARBALL_URL, but with unsafe
+  # characters replaced by underscores.
+  PART_FILE=".meteor-${TARBALL_URL//[^A-Za-z0-9_.-]/_}.part"
+  TARBALL_FILE="$(dirname "$METEOR_WAREHOUSE_DIR")/${PART_FILE}"
+
+  cleanUp() {
+    rm -rf "$TARBALL_FILE"
+    rm -rf "$INSTALL_TMPDIR"
+  }
+
+  # Remove temporary files now in case they exist.
+  cleanUp
+
+  # Make sure cleanUp gets called if we exit abnormally.
+  trap cleanUp EXIT
+
   mkdir "$INSTALL_TMPDIR"
   if [ -n "${USER-}" ]; then
     echo "$USER, this is your first time using Meteor!" 1>&2
@@ -81,12 +97,6 @@ if [ ! -x "$METEOR_WAREHOUSE_DIR/meteor" ]; then
     echo "This is your first time using Meteor!" 1>&2
   fi
   echo "Installing a Meteor distribution in your home directory." 1>&2
-
-  # Generate the $TARBALL_FILE path based on $TARBALL_URL, but with unsafe
-  # characters replaced by underscores.
-  PART_FILE=".meteor-${TARBALL_URL//[^A-Za-z0-9_.-]/_}.part"
-  TARBALL_FILE="$(dirname "$METEOR_WAREHOUSE_DIR")/${PART_FILE}"
-  rm -rf "$TARBALL_FILE"
 
   echo "Downloading Meteor distribution"
   # keep trying to curl the file until it works (resuming where possible)
@@ -115,13 +125,15 @@ if [ ! -x "$METEOR_WAREHOUSE_DIR/meteor" ]; then
   # bomb out if it didn't work, eg no net
   test -e "${TARBALL_FILE}"
   tar -xzf "$TARBALL_FILE" -C "$INSTALL_TMPDIR" -o
-  rm -rf "$TARBALL_FILE"
 
   test -x "${INSTALL_TMPDIR}/.meteor/meteor"
   mv "${INSTALL_TMPDIR}/.meteor" "$METEOR_WAREHOUSE_DIR"
-  rmdir "${INSTALL_TMPDIR}"
   # just double-checking :)
   test -x "$METEOR_WAREHOUSE_DIR/meteor"
+
+  # The `trap cleanUp EXIT` line above won't actually fire after the exec
+  # call below, so call cleanUp manually.
+  cleanUp
 fi
 
 exec "$METEOR_WAREHOUSE_DIR/meteor" "$@"
